import { mkdtempSync, writeFileSync, rmSync, existsSync } from 'fs';
import { tmpdir } from 'os';
import { join, resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { spawnSync } from 'child_process';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PUPPETEER_CONFIG = resolve(__dirname, '../puppeteer-config.json');

/** Locate the mmdc binary: prefer the local node_modules copy, then PATH. */
function findMmdc() {
  const local = resolve(__dirname, '../node_modules/.bin/mmdc');
  if (existsSync(local)) return local;
  const result = spawnSync('which', ['mmdc'], { encoding: 'utf8' });
  if (result.status === 0 && result.stdout.trim()) return result.stdout.trim();
  return null;
}

// Matches fenced mermaid blocks — opening fence must be at line start.
// Group 1: optional info string (e.g. ` caption="Foo" scale=2`)
// Group 2: diagram body
const MERMAID_FENCE = /^```mermaid([^\n]*)\r?\n([\s\S]*?)^```/gm;

/**
 * Parse key=value attributes from a fenced code block info string.
 * Values may be unquoted, single-quoted, or double-quoted.
 * Recognised keys: caption, scale, width, height.
 * width / height are percentage display dimensions passed to pandoc image
 * attributes (e.g. width=80% → {width=80%}) and interpreted by the Lua
 * filter as LaTeX dimensions (0.8\linewidth / 0.8\textheight).
 *
 * @param {string} infoStr - Everything after "mermaid" on the opening fence line.
 * @returns {{ caption?: string, scale?: string, width?: string, height?: string }}
 */
function parseInfoString(infoStr) {
  const result = {};
  const RE = /(\w+)=(?:"([^"]*)"|'([^']*)'|(\S+))/g;
  let m;
  while ((m = RE.exec(infoStr)) !== null) {
    result[m[1]] = m[2] ?? m[3] ?? m[4];
  }
  return result;
}

/**
 * Replace every mermaid code fence in the given Markdown string with a PNG
 * image reference generated by mmdc (mermaid-cli).
 *
 * @param {string} markdownContent  Raw Markdown source.
 * @param {object} [mermaidOptions] Optional rendering options passed to mmdc.
 * @param {string} [mermaidOptions.theme]           Diagram theme (-t).
 * @param {number} [mermaidOptions.scale]           Device scale factor (-s).
 * @param {number} [mermaidOptions.width]           Output width in pixels (-w).
 * @param {number} [mermaidOptions.height]          Output height in pixels (-H).
 * @param {string} [mermaidOptions.backgroundColor] Background colour (-b).
 * @param {string} [mermaidOptions.puppeteerConfig] Path to a Puppeteer config file (-p).
 * @returns {{ content: string, imageDir: string|null }}
 *   `content`  — processed Markdown (unchanged when no mermaid blocks exist).
 *   `imageDir` — temp directory holding the generated images, or `null`.
 *                Call `cleanupMermaid(imageDir)` when the images are no longer needed.
 */
export function preprocessMermaid(markdownContent, mermaidOptions = {}) {
  if (!MERMAID_FENCE.test(markdownContent)) {
    return { content: markdownContent, imageDir: null };
  }
  MERMAID_FENCE.lastIndex = 0; // reset after .test()

  const mmdc = findMmdc();
  if (!mmdc) {
    throw new Error(
      'mmdc not found. Install @mermaid-js/mermaid-cli and ensure it is on PATH.'
    );
  }

  const imageDir = mkdtempSync(join(tmpdir(), 'mermaid-'));
  let index = 0;

  const content = markdownContent.replace(MERMAID_FENCE, (_, infoStr, diagram) => {
    const i = index++;
    const attrs = parseInfoString(infoStr);
    const caption = attrs.caption ?? `Diagram ${i + 1}`;

    const mmdFile = join(imageDir, `diagram-${i}.mmd`);
    const pngFile = join(imageDir, `diagram-${i}.png`);

    writeFileSync(mmdFile, diagram.trimEnd());

    const puppeteerConfig = mermaidOptions.puppeteerConfig || PUPPETEER_CONFIG;
    const mmdc_args = ['-i', mmdFile, '-o', pngFile, '-p', puppeteerConfig];
    if (mermaidOptions.theme) mmdc_args.push('-t', mermaidOptions.theme);
    // Per-diagram scale overrides the global mermaidOptions.scale
    const scale = attrs.scale != null ? parseFloat(attrs.scale) : mermaidOptions.scale;
    if (scale != null) mmdc_args.push('-s', String(scale));
    if (mermaidOptions.width != null) mmdc_args.push('-w', String(mermaidOptions.width));
    if (mermaidOptions.height != null) mmdc_args.push('-H', String(mermaidOptions.height));
    if (mermaidOptions.backgroundColor) mmdc_args.push('-b', mermaidOptions.backgroundColor);

    const result = spawnSync(mmdc, mmdc_args, {
      encoding: 'utf8',
      env: { ...process.env },
    });

    if (result.status !== 0) {
      const stderr = (result.stderr || result.stdout || '').trim();
      throw new Error(`mmdc failed for diagram ${i + 1}: ${stderr}`);
    }

    // Pass display-size percentages as pandoc image attributes so the Lua
    // filter can apply them as LaTeX dimensions (e.g. 80% → 0.8\linewidth).
    const dimParts = [];
    if (attrs.width)  dimParts.push(`width=${attrs.width}`);
    if (attrs.height) dimParts.push(`height=${attrs.height}`);
    const dimStr = dimParts.length > 0 ? `{${dimParts.join(' ')}}` : '';
    return `![${caption}](${pngFile})${dimStr}`;
  });

  return { content, imageDir };
}

/** Remove the temporary image directory created by preprocessMermaid. */
export function cleanupMermaid(imageDir) {
  if (imageDir) {
    rmSync(imageDir, { recursive: true, force: true });
  }
}
