import { mkdtempSync, writeFileSync, rmSync, existsSync } from 'fs';
import { tmpdir } from 'os';
import { join, resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { spawnSync } from 'child_process';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PUPPETEER_CONFIG = resolve(__dirname, '../puppeteer-config.json');

/** Locate the mmdc binary: prefer the local node_modules copy, then PATH. */
function findMmdc() {
  const local = resolve(__dirname, '../node_modules/.bin/mmdc');
  if (existsSync(local)) return local;
  const result = spawnSync('which', ['mmdc'], { encoding: 'utf8' });
  if (result.status === 0 && result.stdout.trim()) return result.stdout.trim();
  return null;
}

// Matches fenced mermaid blocks — opening fence must be at line start.
const MERMAID_FENCE = /^```mermaid\r?\n([\s\S]*?)^```/gm;

/**
 * Replace every mermaid code fence in the given Markdown string with a PNG
 * image reference generated by mmdc (mermaid-cli).
 *
 * @param {string} markdownContent  Raw Markdown source.
 * @returns {{ content: string, imageDir: string|null }}
 *   `content`  — processed Markdown (unchanged when no mermaid blocks exist).
 *   `imageDir` — temp directory holding the generated images, or `null`.
 *                Call `cleanupMermaid(imageDir)` when the images are no longer needed.
 */
export function preprocessMermaid(markdownContent) {
  if (!MERMAID_FENCE.test(markdownContent)) {
    return { content: markdownContent, imageDir: null };
  }
  MERMAID_FENCE.lastIndex = 0; // reset after .test()

  const mmdc = findMmdc();
  if (!mmdc) {
    throw new Error(
      'mmdc not found. Install @mermaid-js/mermaid-cli and ensure it is on PATH.'
    );
  }

  const imageDir = mkdtempSync(join(tmpdir(), 'mermaid-'));
  let index = 0;

  const content = markdownContent.replace(MERMAID_FENCE, (_, diagram) => {
    const i = index++;
    const mmdFile = join(imageDir, `diagram-${i}.mmd`);
    const pngFile = join(imageDir, `diagram-${i}.png`);

    writeFileSync(mmdFile, diagram.trimEnd());

    const result = spawnSync(mmdc, ['-i', mmdFile, '-o', pngFile, '-p', PUPPETEER_CONFIG], {
      encoding: 'utf8',
      env: { ...process.env },
    });

    if (result.status !== 0) {
      const stderr = (result.stderr || result.stdout || '').trim();
      throw new Error(`mmdc failed for diagram ${i + 1}: ${stderr}`);
    }

    return `![Diagram ${i + 1}](${pngFile})`;
  });

  return { content, imageDir };
}

/** Remove the temporary image directory created by preprocessMermaid. */
export function cleanupMermaid(imageDir) {
  if (imageDir) {
    rmSync(imageDir, { recursive: true, force: true });
  }
}
